MVCDemoProject/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCDemoProject.Models
{
    public class Teacher
    {
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAddress { get; set; }
        public string TeacherEmail { get; set; }
        public string TeacherContactNo { get; set; }
        public int DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public decimal TeacherCredit { get; set; }
        public decimal TeacherRemainingCredit { get; set; }

        


    }
}

MVCDemoProject/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using MVCDemoProject.Manager;
using MVCDemoProject.Models;

namespace MVCDemoProject.Controllers
{
    public class TeacherController : Controller
    {
        //
        // GET: /Teacher/

        private DesignationManager designationManager = new DesignationManager();
        private DepartmentManager departmentManager = new DepartmentManager();
        private TeacherManager teacherManager = new TeacherManager();
        private CourseManager courseManager = new CourseManager();
        private CourseAssignManager courseAssignManager=new CourseAssignManager();

      
        [HttpGet]
        public ActionResult Assign()
        {
            ViewBag.Departments = departmentManager.GetAllDepartments();
            return View();
        }

        [HttpPost]
        public ActionResult Assign(CourseAssign courseAssign)
        {
            ViewBag.Message = courseAssignManager.SaveCourseAssign(courseAssign);
            ViewBag.Departments = departmentManager.GetAllDepartments();
         
            //ViewBag.Message1 = teacherManager.UpdateTeacherRemainingCredit(courseAssign.TeacherRemainingCredit);
            return View();
        }


        public JsonResult GetTeacherByDepartmentId(Department department)
        {

            var teacherList = teacherManager.GetAllTeacherByDepartment(department.DepartmentID);
            return Json(teacherList);
        }

        public JsonResult GetCourseByDepartmentId(Department department)
        {
            var courseList = courseManager.GetAllCourseByDepartment(department.DepartmentID);
            return Json(courseList);
        }

        public JsonResult GetTeacherByTeacherId(Teacher teacher)
        {
            var teacherList = teacherManager.GetAllTeacherByTeacherId(teacher.TeacherID);
            return Json(teacherList);
        }

        public JsonResult GetCourseByCourseId(Course course)
        {
            var courseList = courseManager.GetAllCourseByCourseId(course.CourseID);
            return Json(courseList);
        }


        public ActionResult SaveTeacher()
        {
            ViewBag.Designations = designationManager.GetAllDesignations();
            ViewBag.Departments = departmentManager.GetAllDepartments();
            return View();
        }


        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.Message = teacherManager.saveTeacher(teacher);
            ViewBag.Designations = designationManager.GetAllDesignations();
            ViewBag.Departments = departmentManager.GetAllDepartments();
            return View();
        }

       [HttpGet]
        public ActionResult Unassign()
        {
            
            return View();
        }

        [HttpPost]
       public ActionResult Unassign(int? id)
        {
           
           ViewBag.Message = courseAssignManager.CourseUnassign();
          
            return View();
        }





    }
}

MVCDemoProject/Views/Teacher/Assign.cshtml
@using MVCDemoProject.Models

@{
    ViewBag.Title = "Assign";
}

<h2>Course Assign To Teacher</h2>
<form method="POST" id="SaveForm">
    <table>
        <tr>
            <td>
                <label for="departmentId">Select Department</label>
            </td>
            <td>
                <select name="departmentId" id="departmentId">
                    <option value="">Select Department</option>
                    @foreach (Department department in ViewBag.Departments)
                    {
                        <option value="@department.DepartmentID">@department.DepartmentName</option>
                    }
                </select>
            </td>
        </tr>

        <tr>
            <td><label for="TeacherID">Select Teacher</label>
            </td>
            <td>
                <select name="TeacherID" id="TeacherID">
                    <option value="">--Select Teacher-- </option>
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="TeacherCredit">Credit to be taken </label></td>
            <td><input type="text" id="TeacherCredit" name="TeacherCredit"/></td>
        </tr>
        <tr>
            <td><label for="TeacherRemainingCredit">Remaining Credit</label></td>
            <td><input type="text" id="TeacherRemainingCredit" name="TeacherRemainingCredit"/></td>
        </tr>
        <tr>
            <td><label for="courseId">Course Code</label></td>
            <td>
                <select name="courseId" id="courseId">
                    <option value="">--Select Course--</option>
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="CourseName">Name</label></td>
            <td><input type="text" id="CourseName" name="CourseName"/></td>
        </tr>
        <tr>
            <td><label for="CourseCredit">Credit</label></td>
            <td><input type="text" id="CourseCredit" name="CourseCredit"/></td>
        </tr>


        <tr>
            <td></td>
            <td><input type="submit" value="Assign" class="btn btn-default"/></td>
        </tr>
    </table>

</form>
@ViewBag.Message
<br/>
@ViewBag.Message1


@section scripts
{
<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function() {

            $("#departmentId").change(function() {
                var deptId = $("#departmentId").val();
                $("#TeacherID").empty();
                $("#courseId").empty();

                //$("#myTable").hide();
                var json = { departmentId: deptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherByDepartmentId", "Teacher")',
                    //url: '/Department/GetStudentsByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(result) {

                        //alert(result);
                        //$("#myTable").show();
                        $('#TeacherID').append('<option value="">--Select Teacher--</option>');

                        $.each(result, function(key, value) {
                            $('#TeacherID').append('<option value="' + value.TeacherID + '">' + value.TeacherName + '</option>');

                        });

                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDepartmentId", "Teacher")',
                    //url: '/Department/GetStudentsByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(result) {
                        //alert(result);
                        //$("#myTable").show();
                        $('#courseId').append('<option value="">--Select Course--</option>');
                        $.each(result, function(key, value) {
                            $('#courseId').append('<option value="' + value.CourseID + '">' + value.CourseCode + '</option>');


                        });

                    }
                });


            });


            $("#TeacherID").change(function() {
                var teacherId = $("#TeacherID").val();

                var json = { teacherId: teacherId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherByTeacherId", "Teacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    dataType: "json",
                    success: function(data) {
                        $.each(data, function(key, value) {
                            //alert(value.TeacherCredit);
                            $('#TeacherCredit').val(value.TeacherCredit);
                            $('#TeacherRemainingCredit').val(value.TeacherRemainingCredit);


                        });
                    }
                });
            });


            $("#courseId").change(function() {
                var courseId = $("#courseId").val();

                var json = { courseId: courseId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByCourseId", "Teacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    dataType: "json",
                    success: function(data) {
                        $.each(data, function(key, value) {
                            //alert(value.TeacherCredit);
                            $('#CourseName').val(value.CourseName);
                            $('#CourseCredit').val(value.CourseCredit);

                        });
                    }
                });
            });


            $("#SaveForm").submit(function() {
               
                var remainingCredit = $('#TeacherRemainingCredit').val();
                var courseCredit = $('#CourseCredit').val();
                remainingCredit = remainingCredit - courseCredit;

                if (remainingCredit < courseCredit) {
                    if (confirm('Are you sure you want to save this ?')) {
                        $('#TeacherRemainingCredit').val(remainingCredit);
                    } else {
                        // Do nothing!
                    }
                  
                    
                }
                else {
                   
                    //alert(remainingCredit);
                    $('#TeacherRemainingCredit').val(remainingCredit);
                }

            });


            $("#SaveForm").validate({
                rules: {
                    departmentId: "required",

                    TeacherID: "required",
                    courseId: "required",
                },
                messages: {
                    departmentId: "Please Select Department",


                    TeacherID: "Please Select teacher",
                    courseId: "Please Select Course"

                }



            });


        });
    </script>
}

MVCDemoProject/Views/Teacher/SaveTeacher.cshtml
@using MVCDemoProject.Models

@{
    ViewBag.Title = "SaveTeacher";
    List<Designation> designationList = ViewBag.Designations;
    List<Department> departmentList = ViewBag.Departments;
}

<h2>Save Teacher</h2>
<form method="POST" id="SaveTeacher">
    <table>
        <tr>
            <td><label for="TeacherName">Name</label></td>
            <td><input type="text" id="TeacherName" name="TeacherName" /></td>
        </tr>
        <tr>
            <td><label for="TeacherAddress">Address</label></td>
            <td><textarea id="TeacherAddress" name="TeacherAddress" rows="7" cols="21"></textarea></td>
        </tr>
        <tr>
            <td><label for="TeacherEmail">Email</label></td>
            <td><input type="text" id="TeacherEmail" name="TeacherEmail" /></td>
        </tr>
        <tr>
            <td><label for="TeacherContactNo">Contact No</label></td>
            <td><input type="text" id="TeacherContactNo" name="TeacherContactNo" /></td>
        </tr>
        <tr>
            <td><label for="DesignationID">Designation</label></td>
            <td>
                <select id="DesignationID" name="DesignationID">
                    <option value="">Select</option>
                    @foreach (Designation designation in designationList)
                    {
                        <option value="@designation.DesignationID">@designation.DesignationName</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="DepartmentID">Department</label></td>
            <td>
                <select id="DepartmentID" name="DepartmentID">
                    <option value="">Select</option>
                    @foreach (Department department in departmentList)
                    {
                        <option value="@department.DepartmentID">@department.DepartmentName</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="TeacherCredit">Credit to be taken </label></td>
            <td><input type="text" id="TeacherCredit" name="TeacherCredit" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Save" /></td>
        </tr>
    </table>
</form>
@ViewBag.Message
@section scripts
{
<script src="~/Scripts/jquery-1.12.4.js"></script>
   
<script src="~/Scripts/jquery.validate.js"></script>
<script>

    $(document).ready(function () {
        $("#SaveTeacher").validate({
            rules: {
                TeacherName: "required",
                TeacherAddress: "required",
                TeacherEmail: {
                    required: true,
                    email: true
                },
                TeacherContactNo: "required",
                DesignationID: "required",
                DepartmentID: "required",

                TeacherCredit: {
                    required: true,
                    number: true,
                    min: 0

                }
            },
            messages: {
                TeacherName: "Please enter name",
                TeacherAddress: "Please enter address",
                CourseEmail: {
                    required: "Please enter email",
                    email: "Please enter valid email"
                },

                TeacherContactNo: "Enter Contact No",
                DesignationID: "Please Select Designation",
                DepartmentID: "Please Select Department",
                TeacherCredit: {
                    required: "Please enter Course Credit",
                    number: "Please enter a number",
                    minlength: " Credit range must be No negetive value"

                }
            }



        });
    });


</script>

}

MVCDemoProject/Views/Teacher/Unassign.cshtml
@{
    ViewBag.Title = "Unassign";
}

<h2>Unassign</h2>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <form method="POST">
            <input name="submit" type="submit" value="Unassign Courses" class="btn-danger "data-confirm=" are you sure to unassign all courses?"/>
        </form>
        @ViewBag.Message

    </div>
</div>

@section scripts
{
<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

    <script>
    $(document).ready(function () {
        jQuery('[data-confirm]').click(function (e) {
            if (!confirm(jQuery(this).attr("data-confirm"))) {
                e.preventDefault();
            }
        });
    });
</script>
}