MVCDemoProject/Controllers/RoomAllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemoProject.Manager;
using MVCDemoProject.Models;

namespace MVCDemoProject.Controllers
{
    public class RoomAllocationController : Controller
    {

        DepartmentManager departmentManager = new DepartmentManager();
        CourseManager courseManager = new CourseManager();
        RoomManager roomManager=new RoomManager();
        RoomAllocationManager roomAllocationManager=new RoomAllocationManager();
        
        public ActionResult AllocateRoom()
        {
            ViewBag.Departments = departmentManager.GetAllDepartments();
            ViewBag.Courses = courseManager.GetAllCourses();
            ViewBag.Rooms = roomManager.GetAllRoom();
            ViewBag.Days = roomManager.GetAllDays();
            return View();
        }

        [HttpPost]
        public ActionResult AllocateRoom(AllocationRoom allocationRoom)
        {
            ViewBag.SaveRooms= roomAllocationManager.SaveRoomAllocation(allocationRoom);
            ViewBag.Departments = departmentManager.GetAllDepartments();
            ViewBag.Courses = courseManager.GetAllCourses();
            ViewBag.Rooms = roomManager.GetAllRoom();
            ViewBag.Days = roomManager.GetAllDays();
            return View();
        }




        public JsonResult GetCourseByDepartmentId(Department department)
        {
            var courseList = courseManager.GetAllCourseByDepartment(department.DepartmentID);
            return Json(courseList);
        }


        public ActionResult ViewClassScheduleAndRoomAllocation()
        {
            ViewBag.Departments = departmentManager.GetAllDepartments();
            return View();
        }

        public JsonResult ClassScheduleByDepartmentId(int departmentId)
        {
            var courses = courseManager.GetAllCourseByDepartment(departmentId);
            List<object> clsSches = new List<object>();

            foreach (var course in courses)
            {
                var scheduleInfo = roomAllocationManager.GetClassScheduleByDepartmentId(departmentId, course.CourseID);
                if (scheduleInfo == "")
                {
                    scheduleInfo = "Not sheduled yet";
                }


                var clsSch = new
                {
                    CourseCode = course.CourseName,
                    CourseName = course.CourseCode,
                    ScheduleInfo = scheduleInfo
                };
                clsSches.Add(clsSch);
            }

            return Json(clsSches);
        }

        public ActionResult UnAllocateRooms()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnAllocateRooms(int?id)
        {
            //ViewBag.UnallocateRoom = roomAllocationManager.UnalloacteRooms();
            return View();
        }
	}
}

MVCDemoProject/Views/RoomAllocation/AllocateRoom.cshtml
@using MVCDemoProject.Models

@{
    ViewBag.Title = "AllocateRoom";
    List<Department> departmentList = ViewBag.Departments;
    List<Course> courseList = ViewBag.Courses;
    List<Room> roomList = ViewBag.Rooms;
    List<Day> dayList = ViewBag.Days;
}
@section stylesheet
{
<link href="~/Content/jquery.timepicker.css" rel="stylesheet" />
    @*<link href="~/Content/jquery.timepicker.css" rel="stylesheet" />*@
<link href="~/Content/clockface.css" rel="stylesheet" />
}
<h2>Allocate Rooms</h2>

<form method="POST" id="SaveRoom">
    <table>
        <tr>
            <td><label for="DepartmentID">Department</label></td>
            <td>
                <select id="DepartmentID" name="DepartmentID">
                    <option value="">-Select Department-</option>
                    @foreach (Department department in departmentList)
                    {
                        <option value="@department.DepartmentID">@department.DepartmentName</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="CourseID">Course</label></td>
            <td>
                <select id="CourseID" name="CourseID">
                    <option value="">-Select Course-</option>
                    @*@foreach (Course aCourses in courseList)
                        {
                            <option value="@aCourses.CourseID">@aCourses.CourseName</option>
                        }*@
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="RoomId">Room No.</label></td>
            <td>
                <select id="RoomId" name="RoomId">
                    <option value="">-Select Room-</option>
                    @foreach (Room room in roomList)
                    {
                        <option value="@room.RoomId">@room.RoomNo</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="DayId">Day</label></td>
            <td>
                <select id="DayId" name="DayId">
                    <option value="">-Select Day-</option>
                    @foreach (Day days in dayList)
                    {
                        <option value="@days.DayId">@days.DayName</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="FromTime">From</label></td>
            <td><input type="text" id="FromTime" value="0:00 AM" data-format="hh:mm A" class="input-small" name="FromTime"></td>
        </tr>
        <tr>
            <td><label for="ToTime">To</label></td>
            <td><input type="text" id="ToTime" value="0:00 AM" data-format="hh:mm A" class="input-small" name="ToTime"></td>
        </tr>

        <tr>
            <td></td>
            <td><input type="submit" value="Allocate" /></td>
        </tr>
    </table>

</form>
@ViewBag.SaveRooms

@section scripts{
<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

    <script src="~/Scripts/clockface.js"></script>
    <script src="~/Scripts/jquery.timepicker.js"></script>

    @*<script src="~/Scripts/jquery.timepicker.min.js"></script>*@

    <script>
        $(document).ready(function() {
            $('#FromTime').clockface();
            $('#ToTime').clockface();


            $("#DepartmentID").change(function () {
                var deptId = $("#DepartmentID").val();
                $("#CourseID").empty();

                var json = { departmentId: deptId };


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDepartmentId", "RoomAllocation")',
                    //url: '/Department/GetStudentsByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (result) {
                        //alert(result);
                        //$("#myTable").show();
                        $('#CourseID').append('<option value="">--Select Course--</option>');
                        $.each(result, function (key, value) {
                            $('#CourseID').append('<option value="' + value.CourseID + '">' + value.CourseCode + '</option>');


                        });

                    }
                });




            });





            $("#SaveRoom").validate({
                rules: {


                    DepartmentID: "required",
                    CourseID: "required",

                    RoomId: "required",
                    DayId: "required",
                    FromTime: "required",
                    ToTime: "required"

                },
                messages: {


                    DepartmentID: "Please Select Department",
                    CourseID: "Please Select Course",
                    RoomId: "Please Select Room",
                    DayId: "Please Select Day",
                    FromTime: "Please Select Time",
                    ToTime: "Please Select Time"


                }



            });







        });
    </script>


}

MVCDemoProject/Views/RoomAllocation/UnAllocateRooms.cshtml
@{
    ViewBag.Title = "UnAllocat Rooms";
}

<h2>UnAllocateRooms</h2>


<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <form method="POST">
            <input name="submit" type="submit" value="Unallocate Rooms" class="btn-danger " data-confirm=" Are you sure want to unallocate all classroom info ?"/>
        </form>
        @ViewBag.Message

    </div>
</div>
@section scripts
{
<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
    <script>
    $(document).ready(function () {
        jQuery('[data-confirm]').click(function (e) {
            if (!confirm(jQuery(this).attr("data-confirm"))) {
                e.preventDefault();
            }
        });
    });
</script>
}

MVCDemoProject/Views/RoomAllocation/ViewClassScheduleAndRoomAllocation.cshtml
@using MVCDemoProject.Models

@{
    ViewBag.Title = "ViewClassScheduleAndRoomAllocation";
    List<Department> departmentList = ViewBag.Departments;
        
}

<h2>View Class Schedule And Room Allocation  </h2>
<form method="POST">

    <table>
        <tr>
            <td><label for="DepartmentID">Department</label></td>
            <td>
                <select id="DepartmentID" name="DepartmentID">
                    <option value="">Select</option>
                    @foreach (Department department in departmentList)
                    {
                        <option value="@department.DepartmentID">@department.DepartmentName</option>
                    }
                </select>
            </td>
        </tr>
    </table>
    <table class="table-bordered" id="statistic">
        <thead>

            <tr>
                <th>Course Code</th>
                <th> Course Name</th>
                <th> Schedule Info</th>
               


            </tr>
        </thead>
        <tbody id="allocationStatistic"> </tbody>
    </table>
</form>

@section scripts
{
    <script>
        $(document).ready(function () {

            $("#DepartmentID").change(function () {
                var deptId = $("#DepartmentID").val();
                $('#allocationStatistic').empty();
                var json = { DepartmentID: deptId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ClassScheduleByDepartmentId", "RoomAllocation")',
                    //url: '/Department/GetStudentsByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (result) {

                        //alert(result);
                        //$("#myTable").show();
                        $.each(result, function (key, value) {


                            //alert(value.TeacherName);


                            $('#allocationStatistic').append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.ScheduleInfo + '</td></tr>');




                            //$('#courseStatistic').append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.SemesterName + '</td><td>Not assigned</td></tr>');

                            //$('#courseStatistic').append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.SemesterName + '</td><td>'+value.TeacherName+'</td></tr>');

                        });

                    }

                });


            });


        });

    </script>
     
}